// GENERATED by frontend/scripts/fixtures/make_text2voxel_fixtures.py - do not edit.
//
// Character classes probed from the HF `tokenizers` build the training data was
// tokenised with, so the browser tokenizer does not depend on the browser's own
// Unicode tables. Each table is a list of inclusive code-point ranges, stored as
// base-36 "gap.length" pairs (gap from the previous range's end).

/** Removed by BertNormalizer clean_text (NUL, U+FFFD, control/format/private-use). */
export const REMOVED = '0.8,3.1,2.h,2o.w,e.0,11v.5,n.0,5d.0,1e.0,3cv.0,1kt.4,r.4,1e.4,2.9,11u9.4xr,16o.0,6y.2,2.0,3b4.0,xyb.3,440.7,h407.0,v.2n,1egx.1ekd,3.1ekd'

/** Mapped to a plain space by clean_text; also split points for the pre-tokenizer. */
export const WHITESPACE = '9.1,3.0,43.0,4bk.0,1vk.a,u.1,6.0,1c.0,335.0'

/** Padded with spaces by handle_chinese_chars (note: HF starts Ext-E at U+2B920). */
export const CHINESE = 'a9s.533,1t.g73,hkx.e7,1fk1.wyn,x.3dr,75.49b,85t.f3'

/** Non-spacing marks dropped by strip_accents after NFD. */
export const MARKS = 'lc.33,7o.4,7e.18,2.0,2.1,2.1,2.0,21.a,1d.k,h.0,2u.6,3.5,3.1,2.3,10.0,v.q,2k.a,1n.8,z.3,2.8,2.2,2.4,18.2,3s.v,1k.0,2.0,5.7,5.0,4.6,b.1,u.0,1n.0,5.3,9.0,l.1,u.1,1m.0,5.1,5.1,3.2,4.0,v.1,4.0,c.1,1m.0,5.4,2.1,5.0,l.1,u.0,1n.0,3.0,2.3,9.0,9.0,c.1,v.0,1q.0,d.0,1f.0,1q.2,6.2,2.3,8.1,c.1,u.0,1n.0,3.0,7.0,6.1,l.1,u.0,1s.3,9.0,l.1,2v.0,8.2,2.0,2j.0,3.6,d.7,2r.0,3.5,2.1,c.5,23.1,s.0,2.0,2.0,1k.d,2.4,2.1,6.a,2.z,a.0,2v.3,2.5,2.1,3.1,q.1,5.2,h.3,e.0,3.1,7.0,g.0,jk.2,qb.2,u.2,u.1,v.1,1t.1,2.6,9.0,3.a,a.0,1a.2,4c.0,3b.2,5.1,a.0,7.2,64.1,3.0,1n.0,2.6,2.0,2.0,3.7,7.9,3.0,1d.d,1v.3,1d.0,2.4,2.0,6.0,15.8,d.1,x.3,3.1,2.2,1l.0,2.1,4.0,2.2,1n.7,3.1,49.2,2.c,2.6,5.0,7.0,4.1,5j.1h,7.3,k1.c,5.0,4.b,2db.2,3y.0,2p.v,ff.3,30.1,n9x.0,5.9,x.1,29.1,7l.0,4.0,5.0,q.1,4e.0,s.h,1h.7,q.a,1b.2,1d.0,3.3,3.0,15.0,1w.5,3.1,3.1,d.0,9.0,1c.0,1g.0,2.2,3.1,6.1,2.0,17.1,9.0,6n.0,3.0,5.0,fn5.0,ki.f,h.f,r2.0,6b.0,46.4,1af.2,2.1,6.3,15.2,5.0,4m.1,10b.0,1j.e,1l.2,1e.3,3.1,1y.2,11.4,2.7,1r.0,d.1,1h.8,c.2,2r.2,3.0,2.1,4o.0,4.7,m.1,1n.0,4.0,12.6,4.4,8v.5,2.0,5.1,2.1,6n.3,7.1,2.1,s.1,2e.7,3.0,2.1,2z.0,2.0,3.5,2.0,2u.2,3.3,2.4,gjp.4,1o.6,ux.3,f7v.1,43t.2,i.7,3.6,v.3,45.2,1j0.1i,5.1d,9.0,f.0,n.4,2.e,2sh.6,gzl6.6n'

/** Isolated as single-character tokens by BertPreTokenizer (ASCII punct + Unicode P*). */
export const PUNCTUATION = 'x.e,b.6,r.5,r.3,z.0,6.0,4.0,b.1,4.0,4.0,jj.0,9.0,cz.5,16.1,1g.0,2.0,3.0,3.0,19.1,l.1,2.1,e.0,3.1,23.3,2v.0,18.d,6i.2,1j.e,w.0,7a.1,b.0,ao.0,lg.0,2j.0,b.1,4p.e,2.0,12.3,20.0,23.4,5.1,34.5,4s.0,h1.8,48.0,h9.1,19.1,27.2,20.1,4e.2,2.2,12.a,8q.1,61.1,3l.6,2.5,4t.6,4c.3,1o.4,1r.1,1t.7,c.0,n1.n,9.j,2.c,2.b,v.1,f.1,hm.3,u.1,u6.d,28.1,w.9,b8.l,1s.3,x.1,l8.3,2.1,35.0,40.1a,2.i,cf.2,5.9,3.b,h.0,d.0,2r.0,2j.0,mwz.1,7i.2,2s.0,b.0,38.5,al.3,2f.1,15.2,2.0,1e.1,1c.0,2q.c,h.1,3h.3,3j.1,h.1,6y.0,g2b.1,5t.9,n.y,2.d,2.0,5.0,2.1,46.2,2.5,2.3,b.1,4.1,r.2,2.0,s.0,2.0,2.6,bf.2,il.0,1d.0,bj.0,ko.0,5k.0,w.0,7l.8,13.0,35.6,1v.6,2i.3,x7.6,32.1,2.3,3j.3,1d.1,28.4,4.0,e.0,2.2,2h.5,30.0,f1.0,6z.m,2y.2,6x.2,2lu.4,dtm.1,3q.0,1u.4,9.0,g2j.0,5wo.4'

/** Split points for BertPreTokenizer (Rust char::is_whitespace). */
export const SPLIT_SPACE = '9.4,j.0,2t.0,r.0,4bk.0,1vk.a,u.1,6.0,1c.0,335.0'

/**
 * Code points the Rust NFD decomposes. Browsers ship newer Unicode tables
 * that also decompose characters added since, so NFD is applied only to these.
 */
export const DECOMPOSE = '5c.5,2.8,2.5,3.4,3.5,2.8,2.5,3.4,2.g,3.j,3.8,4.3,2.5,5.5,4.5,3.h,3.m,y.1,e.1,t.f,2.5,3.a,4.1,3.z,3.1,7.d,7h.1,2.1,1c.0,a.0,7.5,2.0,2.2,q.6,q.4,5.1,18.1,2.0,4.0,5.2,b.0,w.0,n.1,2.0,4.0,5.2,o.1,22.1,e.3,3.1,3.5,3.5,3.b,3.1,89.4,4a.0,2.0,h.0,gm.0,8.0,3.0,10.7,30.1,g.1,2.0,2c.0,3.0,z.2,3.0,6i.0,3.1,g.1,1j.0,1i.2,3g.0,3c.0,7.1,2.1,3j.2,3y.0,2.2,9x.0,a.0,5.0,5.0,5.0,d.0,a.0,2.1,2.0,9.0,i.0,a.0,5.0,5.0,5.0,d.0,31.0,25c.0,2.0,2.0,2.0,2.0,4.0,15.0,2.0,3.1,2.0,jh.49,2.0,5.2h,7.l,3.5,3.11,3.5,3.7,2.0,2.0,2.0,2.u,3.1g,2.6,2.0,3.3,2.d,3.5,2.i,3.2,2.7,3.1,85.0,4.1,33.1,j.0,v.2,1h.0,5.0,3.0,o.0,2.0,r.0,3.0,3.0,2.0,n.0,2.0,b.4,3.1,3.1,7.1,3.1,3.1,z.3,1d.3,7.3,1o.1,1iq.0,12o.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,3.0,2.0,2.0,7.1,2.1,2.1,2.1,2.1,n.0,a.0,e.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,3.0,2.0,2.0,7.1,2.1,2.1,2.1,2.1,n.0,3.3,4.0,oaq.8mb,6l9.7h,3.0,2.0,3.9,2.0,2.0,3.1,4.1v,3.2x,1w.0,2.0,b.c,2.4,2.0,2.1,2.1,2.8,47g.0,2.0,f.0,3n.1,f0.1,a7.1,2.0,70.1,112b.6,2f.5,1m4g.f1'
