"""Assemble single-file Kaggle kernels from ``common.py`` + a stage script.

    python training/text2voxel/build_kernels.py          # writes kaggle/<stage>/kernel.py
    python -m kaggle kernels push -p training/text2voxel/kaggle/k1

Kaggle script kernels cannot import sibling modules, so the shared module is
inlined ahead of the stage code (with a single ``from __future__`` import).
"""

from __future__ import annotations

import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
OWNER = "arunkumarpucha"

KERNELS = {
    "k1": {
        "script": "k1_prep.py",
        "slug": "text2voxel-k1-prep",
        "title": "Text2Voxel K1 Prep",
        "gpu": False,
        "internet": True,
        "datasets": ["balraj98/modelnet40-princeton-3d-object-dataset"],
        "kernels": [],
    },
    "k2": {
        "script": "k2_train.py",
        "slug": "text2voxel-k2-train",
        "title": "Text2Voxel K2 Train",
        "gpu": True,
        "internet": True,
        "datasets": [],
        "kernels": [f"{OWNER}/text2voxel-k1-prep"],
    },
}

FUTURE = "from __future__ import annotations"


def strip_future(source: str) -> str:
    return "\n".join(line for line in source.splitlines() if line.strip() != FUTURE)


def build(name: str, spec: dict) -> Path:
    common = strip_future((HERE / "common.py").read_text(encoding="utf-8"))
    stage = strip_future((HERE / spec["script"]).read_text(encoding="utf-8"))
    body = (
        f"{FUTURE}\n"
        f"# Generated by training/text2voxel/build_kernels.py - edit the sources, not this file.\n"
        f"# ---- common.py ----\n{common}\n"
        f"# ---- {spec['script']} ----\n{stage}\n"
    )
    target = HERE / "kaggle" / name
    target.mkdir(parents=True, exist_ok=True)
    (target / "kernel.py").write_text(body, encoding="utf-8")
    metadata = {
        "id": f"{OWNER}/{spec['slug']}",
        "title": spec["title"],
        "code_file": "kernel.py",
        "language": "python",
        "kernel_type": "script",
        "is_private": True,
        "enable_gpu": spec["gpu"],
        "enable_tpu": False,
        "enable_internet": spec["internet"],
        "keywords": [],
        "dataset_sources": spec["datasets"],
        "kernel_sources": spec["kernels"],
        "competition_sources": [],
        "model_sources": [],
    }
    if spec["gpu"]:
        metadata["machine_shape"] = "NvidiaTeslaT4"
    (target / "kernel-metadata.json").write_text(json.dumps(metadata, indent=2) + "\n",
                                                 encoding="utf-8")
    compile(body, str(target / "kernel.py"), "exec")
    return target


if __name__ == "__main__":
    for kernel_name, kernel_spec in KERNELS.items():
        if (HERE / kernel_spec["script"]).exists():
            print("built", build(kernel_name, kernel_spec))
